version: '3'

services:
  redis:
    build: ./redis
    restart: always
    ports:
      - "6379:6379"

  # mysql:
  #   build: ./mysql
  #   restart: always

  postgres:
    build: ./postgresql
    restart: always
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    env_file: .env
    expose:
      - "5000"
    volumes:
      - ./app/static:/usr/src/app/static
      - ./articles:/home/flasky/web/articles
    command: /bin/bash ./boot.sh
    depends_on:
      - redis
      - postgres

  celery:
    build: .
    restart: always
    env_file: .env
    command: celery worker -A celery_worker.celery --loglevel=info
    depends_on:
      - redis
      - web

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      - ./app/static:/usr/src/app/static
    depends_on:
      - web
