"""save article body(md) and author in Article

Revision ID: 0abd9fd52d45
Revises: e6d1b6a3140c
Create Date: 2017-06-16 17:06:30.386608

"""

# revision identifiers, used by Alembic.
revision = '0abd9fd52d45'
down_revision = 'e6d1b6a3140c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('body_html', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'body_html')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
