"""fix word location

Revision ID: 2c42d3d4591d
Revises: 532b69010c42
Create Date: 2018-04-27 19:26:22.495935

"""

# revision identifiers, used by Alembic.
revision = '2c42d3d4591d'
down_revision = '532b69010c42'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('value', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_words_value'), 'words', ['value'], unique=True)
    op.drop_index('ix_words_word', table_name='words')
    op.drop_column('words', 'word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('word', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_words_word', 'words', ['word'], unique=True)
    op.drop_index(op.f('ix_words_value'), table_name='words')
    op.drop_column('words', 'value')
    # ### end Alembic commands ###
