"""add user confirmed

Revision ID: 56a9037e0e5d
Revises: f6d1fc6c10da
Create Date: 2017-04-23 10:22:56.521875

"""

# revision identifiers, used by Alembic.
revision = '56a9037e0e5d'
down_revision = 'f6d1fc6c10da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
