"""add article info

Revision ID: 6951af5b541d
Revises: ba4257eef52d
Create Date: 2016-10-23 19:10:02.347411

"""

# revision identifiers, used by Alembic.
revision = '6951af5b541d'
down_revision = 'ba4257eef52d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('md5', sa.String(length=64), nullable=True))
    op.add_column('articles', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'articles', ['md5'])
    op.create_unique_constraint(None, 'articles', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'name')
    op.drop_column('articles', 'md5')
    ### end Alembic commands ###
