"""add timestamp in article

Revision ID: 8ad0924326ad
Revises: 0abd9fd52d45
Create Date: 2017-06-21 16:32:44.005780

"""

# revision identifiers, used by Alembic.
revision = '8ad0924326ad'
down_revision = '0abd9fd52d45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_articles_timestamp'), 'articles', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_timestamp'), table_name='articles')
    op.drop_column('articles', 'timestamp')
    # ### end Alembic commands ###
