"""initial migration

Revision ID: ba4257eef52d
Revises: None
Create Date: 2016-10-23 17:59:30.994659

"""

# revision identifiers, used by Alembic.
revision = 'ba4257eef52d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    ### end Alembic commands ###
