"""add body field for article

Revision ID: cd3b2c4fb282
Revises: 481cae04b281
Create Date: 2017-05-08 15:11:42.660488

"""

# revision identifiers, used by Alembic.
revision = 'cd3b2c4fb282'
down_revision = '481cae04b281'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body')
    # ### end Alembic commands ###
