"""Prune Tag, Category, Article datasheet

Revision ID: e4e7040f27ce
Revises: e1919971bdcd
Create Date: 2018-04-15 13:31:15.425304

"""

# revision identifiers, used by Alembic.
revision = 'e4e7040f27ce'
down_revision = 'e1919971bdcd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'datestr')
    op.drop_column('categories', 'size')
    op.drop_column('tags', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('datestr', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
