"""add date for article

Revision ID: e66ba548fa14
Revises: 56a9037e0e5d
Create Date: 2017-04-27 21:39:31.163618

"""

# revision identifiers, used by Alembic.
revision = 'e66ba548fa14'
down_revision = '56a9037e0e5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles") as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('datestr', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'articles', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'datestr')
    op.drop_column('articles', 'date')
    # ### end Alembic commands ###
