"""add name for user

Revision ID: e6d1b6a3140c
Revises: 418106ae2e3f
Create Date: 2017-06-16 14:36:58.509939

"""

# revision identifiers, used by Alembic.
revision = 'e6d1b6a3140c'
down_revision = '418106ae2e3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
